" ~/.vim/gvimrc

set columns=80
set lines=35

set cursorline

set guicursor=i-ci:hor15,r-cr:hor30,a:blinkon0
set title

if has('gui_gtk')
  set guifont=DejaVu\ Sans\ Mono\ 12
elseif has('gui_win32')
  set guifont=Courier_New:h12:cRUSSIAN
endif
set guioptions-=e guioptions-=T guioptions-=r guioptions-=L guioptions+=c

set t_vb=

behave xterm

map <S-Insert> <MiddleMouse>
map! <S-Insert> <MiddleMouse>

" vim:set shiftwidth=2:
