" ~/.vim/gvimrc

set columns=100 lines=35

set guicursor=i-ci:hor15,r-cr:hor30,a:blinkon0
set title

if has('gui_gtk')
  set guifont=DejaVu\ Sans\ Mono\ 14
elseif has('gui_win32')
  set guifont=Consolas:h14:cRUSSIAN,Courier_New:h14:cRUSSIAN
endif
set guioptions-=e guioptions-=T guioptions-=r guioptions-=L guioptions+=c

set t_vb=

behave xterm

noremap  <S-Insert> <MiddleMouse>
noremap! <S-Insert> <MiddleMouse>
