" ~/.vim/vimrc

language messages C

runtime bundle/pathogen/autoload/pathogen.vim
silent! execute pathogen#infect()

if empty(&termencoding)
  let &termencoding = exists('$MSYSTEM') ? 'cp1251' : &encoding
endif
set encoding=utf-8
set fileencodings=ucs-bom,utf-8,cp1251

set pastetoggle=<F2>

set incsearch
set ignorecase smartcase

set tags=./tags;,tags

set scrolloff=1
if has('patch-7.4.338')
  set breakindent breakindentopt=sbr
endif
set showbreak=+
set sidescrolloff=5
set display=lastline
set cmdheight=2
set listchars=eol:$,tab:>-,trail:-,extends:>,precedes:<,nbsp:%

set background=dark
set hlsearch
set spelllang=en_us,ru_yo

set laststatus=2
set statusline=%n\ %<%.20f\ %h%m%r%{line#flags()}%=%-14.(%l,%c%V%)\ %P

set tabline=%!line#tabline()

set notitle

if has('mouse')
  set mouse=a
endif

set showcmd
set visualbell t_vb=

set undofile
set backspace=indent,eol,start
if has('patch-7.3.541')
  set formatoptions+=j
endif
set complete-=i complete-=t
set completeopt-=preview
set infercase
set nrformats-=octal

set shiftwidth=4
set softtabstop=4
set expandtab
set autoindent

if has('folding')
  set foldopen+=jump
endif

set timeoutlen=3000
set ttimeoutlen=100

set modeline
if has('patch-7.4.785')
  set nofixendofline
endif
set backup
set autowrite
set autoread

set history=200
set wildmode=longest:full,full
set wildmenu

if executable('ack')
  set grepprg=ack\ -H\ --column grepformat=%f:%l:%c:%m,%f:%l:%m
endif

set keymap=russian-hash
set iminsert=0 imsearch=-1

set virtualedit=block
set sessionoptions-=blank sessionoptions-=options
set viminfo=!,'20,<50,s10,h

syntax on
filetype plugin indent on

augroup colorscheme
  autocmd!
  autocmd ColorScheme off highlight link diffRemoved DiffDelete
  autocmd ColorScheme off highlight link diffAdded   DiffAdd
augroup END

silent! colorscheme off

let g:user_emmet_leader_key = '<C-\>'

let g:line_flags = ['fugitive#statusline', 'SyntasticStatuslineFlag']

let g:netrw_bufsettings = 'noma nomod nonu nobl nowrap ro rnu'
let g:netrw_banner = 0
let g:netrw_list_hide = '\v\C%(\~|\.swp)\*?$'
let g:netrw_timefmt = '%a %d %b %Y %H:%M:%S'

let g:sneak#s_next = 1
let g:sneak#map_netrw = 0

let g:surround_56 = "/* \r */"

let g:syntastic_check_on_wq = 0
let g:syntastic_stl_format = '[Syn(%t)]'

let g:tern#command = ['tern', '--no-port-file']
let g:tern_show_signature_in_pum = 1

let g:vdebug_options = {
      \ 'watch_window_style': 'compact',
      \ 'marker_default': '*',
      \ 'marker_closed_tree': '+',
      \ 'marker_open_tree': '-',
      \ 'continuous_mode': 1,
      \ }

let g:c_no_curly_error = 1
let g:c_syntax_for_h = 1
let g:c_no_comment_fold = 1

let g:go_highlight_trailing_whitespace_error = 0
if executable('goimports')
  let g:gofmt_command = 'goimports'
endif

let g:html_no_rendering = 1
let g:html_indent_autotags = 'html'
let g:html_indent_script1 = 'auto'
let g:html_indent_style1 = 'auto'

let g:perl_fold = 1

let g:php_folding = 1

let g:ruby_fold = 1
let g:ruby_no_comment_fold = 1

let g:is_posix = 1
let g:sh_fold_enabled = 3

if has('digraphs')
  " Horizontal ellipsis
  digraphs ,. 8230
endif

cnoremap <C-X>n <Down>
cnoremap <C-X>p <Up>

inoremap <C-U> <C-G>u<C-U>

nnoremap + <C-W>+
nnoremap _ <C-W>-

nnoremap - :Explore<CR>

nnoremap <F3> :mksession! <C-R>=fnameescape(v:this_session)<CR><CR>

nnoremap <Tab>  <C-W>w
nnoremap g<Tab> <C-W>W

nnoremap <silent> <C-L> :nohlsearch<CR><C-L>

nnoremap Q @@

nnoremap gj j
nnoremap gk k

nnoremap j gj
nnoremap k gk

noremap! <F4> <C-^>

if exists('#fedora')
  autocmd! fedora BufReadPost *
endif

runtime macros/matchit.vim
